export default {
  LOGIN_USER_REQUEST: 'ACTION_LOGIN_USER_REQUEST',
  LOGIN_USER_PENDING: 'ACTION_LOGIN_USER_PENDING',
  LOGIN_USER_RESPONSE: 'ACTION_LOGIN_USER_RESPONSE',
  LOGIN_USER_ERROR: 'ACTION_LOGIN_USER_ERROR',

  LOGOUT_USER_REQUEST: 'ACTION_LOGOUT_USER_REQUEST',
  LOGOUT_USER_PENDING: 'ACTION_LOGOUT_USER_PENDING',
  LOGOUT_USER_RESPONSE: 'ACTION_LOGOUT_USER_RESPONSE',
  LOGOUT_USER_ERROR: 'ACTION_LOGOUT_USER_ERROR',

  REGISTER_USER_REQUEST: 'ACTION_REGISTER_USER_REQUEST',
  REGISTER_USER_PENDING: 'ACTION_REGISTER_USER_PENDING',
  REGISTER_USER_RESPONSE: 'ACTION_REGISTER_USER_RESPONSE',
  REGISTER_USER_ERROR: 'ACTION_REGISTER_USER_ERROR',

  RETRIEVE_GOODS_REQUEST: 'ACTION_RETRIEVE_GOODS_REQUEST',
  RETRIEVE_GOODS_PENDING: 'ACTION_RETRIEVE_GOODS_PENDING',
  RETRIEVE_GOODS_RESPONSE: 'ACTION_RETRIEVE_GOODS_RESPONSE',
  RETRIEVE_GOODS_ERROR: 'ACTION_RETRIEVE_GOODS_ERROR',
};
