export default {
  LOGIN_USER_REQUEST: 'ACT_LOGIN_USER_REQUEST',
  LOGIN_USER_PENDING: 'ACT_LOGIN_USER_PENDING',
  LOGIN_USER_RESPONSE: 'ACT_LOGIN_USER_RESPONSE',

  LOGOUT_USER_REQUEST: 'ACT_LOGOUT_USER_REQUEST',
  LOGOUT_USER_PENDING: 'ACT_LOGOUT_USER_PENDING',
  LOGOUT_USER_RESPONSE: 'ACT_LOGOUT_USER_RESPONSE',

  REGISTER_USER_REQUEST: 'ACT_REGISTER_USER_REQUEST',
  REGISTER_USER_PENDING: 'ACT_REGISTER_USER_PENDING',
  REGISTER_USER_RESPONSE: 'ACT_REGISTER_USER_RESPONSE',

  RETRIEVE_GOODS_REQUEST: 'ACT_RETRIEVE_GOODS_REQUEST',
  RETRIEVE_GOODS_PENDING: 'ACT_RETRIEVE_GOODS_PENDING',
  RETRIEVE_GOODS_RESPONSE: 'ACT_RETRIEVE_GOODS_RESPONSE',
};
