export default {
  SET_USER_INFO: 'MUTATION_SET_USER_INFO',
  SET_USER_CREDENTIAL: 'MUTATION_SET_USER_CREDENTIAL',
  CLEAR_USER: 'MUTATION_CLEAR_USER',
  APPEND_GOODS: 'MUTATION_APPEND_GOODS',
  REMOVE_GOODS: 'MUTATION_REMOVE_GOODS',
  UPDATE_GOODS: 'MUTATION_UPDATE_GOODS',
  APPEND_ORDER: 'MUTATION_APPEND_ORDER',
  REMOVE_ORDER: 'MUTATION_REMOVE_ORDER',
  UPDATE_ORDER: 'MUTATION_UPDATE_ORDER',
};
